name: Generate long-term charts (R-BANK9)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: List BEFORE
        run: |
          echo "CWD=$(pwd)"
          mkdir -p docs/outputs
          ls -lah
          ls -lah docs/outputs || true

      - name: Generate long-term charts
        env:
          INDEX_KEY: rbank9
        run: |
          python scripts/long_charts.py
          echo "---- AFTER DRAW ----"
          ls -lah docs/outputs || true
          # 生成必須チェック（1d）
          test -f docs/outputs/rbank9_1d.png || (echo "rbank9_1d.png not created" && exit 1)
          # 指名漏れ/命名ミス検知用に一覧出力
          echo "PNG list:"
          find docs/outputs -maxdepth 1 -type f -name "*.png" -printf "%P\n" || true

      - name: Upload charts artifact
        uses: actions/upload-artifact@v4
        with:
          name: rbank9-charts
          path: docs/outputs/*.png
          if-no-files-found: error
          retention-days: 7

      - name: List AFTER
        run: |
          ls -lah docs/outputs || true
          git status --porcelain

      - name: Commit charts if changed (force add to bypass .gitignore)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --global safe.directory "$(pwd)"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 直前の更新を安全に取り込み
          git pull --rebase || true

          # .gitignore で弾かれても add できるように -f
          git add -f docs/outputs/*.png 2>/dev/null || true

          # ステージングされているか確認
          if git diff --cached --quiet; then
            echo "No staged PNG changes (likely identical content or not generated)."
            echo "Listing files for debugging:"
            git ls-files -v docs/outputs | cat
            exit 0
          fi

          git commit -m "chore(charts): update R-BANK9 long-term charts (1d/7d/1m/1y)"
          git push

