name: Generate long-term charts

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: long-charts-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # リポジトリ名 → INDEX_KEY と マーケット設定
      - name: Resolve INDEX_KEY & market
        id: resolve
        shell: bash
        run: |
          set -euo pipefail
          REPO_RAW="${GITHUB_REPOSITORY##*/}"            # 例: AIN-10 / S-COIN- / R-BANK9 / 3_Sakura_Space
          REPO_LC="$(echo "$REPO_RAW" | tr '[:upper:]' '[:lower:]')"

          case "$REPO_LC" in
            3_sakura_space) KEY="astra4";   TZ="Asia/Tokyo";         S="09:00"; E="15:30" ;;
            s-coin-)        KEY="scoin_plus";TZ="Asia/Tokyo";         S="09:00"; E="15:30" ;; # 株式関連
            r-bank9)        KEY="rbank9";    TZ="Asia/Tokyo";         S="09:00"; E="15:30" ;;
            ain-10)         KEY="ain10";     TZ="America/New_York";  S="09:30"; E="16:00" ;;
            *)              KEY="index";     TZ="UTC";                S="00:00"; E="23:59" ;;
          esac

          echo "INDEX_KEY=$KEY" | tee -a "$GITHUB_ENV"
          echo "market_tz=$TZ"   | tee -a "$GITHUB_OUTPUT"
          echo "session_start=$S"| tee -a "$GITHUB_OUTPUT"
          echo "session_end=$E"  | tee -a "$GITHUB_OUTPUT"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clear pycache
        run: rm -rf scripts/__pycache__ || true

      - name: Generate long-term charts
        env:
          INDEX_KEY: ${{ env.INDEX_KEY }}
          CLAMP_SESSION: "true"
          MARKET_TZ: ${{ steps.resolve.outputs.market_tz }}
          SESSION_START: ${{ steps.resolve.outputs.session_start }}
          SESSION_END:   ${{ steps.resolve.outputs.session_end }}
        run: |
          set -euo pipefail
          python scripts/long_charts.py

      # ファイル名の接頭辞チェック（KEY一致）
      - name: Sanity check: filenames prefix
        env:
          INDEX_KEY: ${{ env.INDEX_KEY }}
        shell: bash
        run: |
          set -euo pipefail
          OUTDIR="docs/outputs"
          mismatched=0
          shopt -s nullglob
          for f in "$OUTDIR"/*; do
            base="$(basename "$f")"
            [[ "$base" == "${INDEX_KEY}_"* ]] || { echo "❌ prefix mismatch: $base"; mismatched=1; }
          done
          [ $mismatched -eq 0 ] || { echo "Prefix mismatch (INDEX_KEY=$INDEX_KEY)"; exit 1; }
          echo "✅ Prefix check passed."

      - name: List outputs
        run: |
          echo "=== outputs ==="
          ls -lah docs/outputs || true

      - name: Commit charts if changed
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/outputs/*.png docs/outputs/*history.csv docs/outputs/*_post_intraday.txt docs/outputs/*_stats.json 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(charts): update long-term charts (1d/7d/1m/1y) & stats"
            git push
          fi
