name: Generate long-term charts (R-BANK9)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: List BEFORE
        run: |
          pwd
          ls -lah
          ls -lah docs/outputs || true

      - name: Generate long-term charts
        env:
          INDEX_KEY: rbank9   # ← 小文字＆アンダースコア無しで統一
        run: python scripts/long_charts.py

      - name: List AFTER
        run: |
          echo "CWD=$(pwd)"
          ls -lah docs/outputs
          git status --porcelain

      - name: Commit charts if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/outputs/*.png || true
          git commit -m "chore(charts): update R-BANK9 long-term charts (1d/7d/1m/1y)" || echo "no changes"
          git push || true
