name: Generate long-term charts (R-BANK9)
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Generate long-term charts
        env:
          INDEX_KEY: rbank9
        run: |
          mkdir -p docs/outputs
          python scripts/long_charts.py
          echo "---- AFTER DRAW ----"
          ls -lah docs/outputs || true

      - name: Force commit and push charts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase || true
          git add -f docs/outputs/*.png || true
          git commit -am "force update: long-term charts (R-BANK9)" || echo "no commit"
          git push --force
