name: Generate long-term charts (R-BANK9 7d/1m/1y)

on:
  schedule:
    - cron: '05 1 * * *'     # 10:05 JST
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: long-charts-${{ github.ref }}
  cancel-in-progress: false

jobs:
  long:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      INDEX_KEY: rbank9
      OUT_DIR: docs/outputs

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: true }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: pip install --upgrade pip && pip install pandas matplotlib

      - name: Generate 7d/1m/1y charts
        run: |
          python scripts/long_charts.py
          ls -lah "$OUT_DIR" || true

      - name: Commit charts
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$OUT_DIR"/rbank9_{7d,1m,1y}.png "$OUT_DIR"/_last_run.txt
          if git diff --cached --quiet; then
            echo "No chart updates."
          else
            git commit -m "chore(rbank9): update long-term charts (7d/1m/1y)"
            git push
          fi
