name: R-BANK9 • close (append history)

on:
  schedule:
    - cron: '00 6 * * 1-5'   # 15:00 JST ＝ 06:00 UTC（必要に応じ調整）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  close:
    runs-on: ubuntu-latest
    env:
      INDEX_KEY: rbank9
      OUT_DIR: docs/outputs

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: true }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: pip install --upgrade pip && pip install pandas

      # もしこの時点で rbank9_stats.json が更新されていなければ、
      # intraday.csv から推定して history に追記（保険）
      - name: Append today to history
        run: |
          python scripts/append_history.py
          tail -n 5 "$OUT_DIR/rbank9_history.csv" || true

      - name: Commit history
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$OUT_DIR/rbank9_history.csv"
          if git diff --cached --quiet; then
            echo "No history changes."
          else
            git commit -m "chore(rbank9): append history (close)"
            git push
          fi
