name: Generate long-term charts (R-BANK9 7d/1m/1y + stats)

on:
  workflow_dispatch:
  schedule:
    - cron: '05 1 * * *'   # 10:05 JST（引け後）

permissions:
  contents: write

concurrency:
  group: long-charts-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      INDEX_KEY: rbank9
      OUT_DIR: docs/outputs
      MARKET_TZ: Asia/Tokyo

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pandas matplotlib; fi

      # 履歴ファイルは外部ワークフロー等で蓄積していく前提
      # ここでは存在チェックのみ（無ければ空のままグラフは「Insufficient history」表示）
      - name: Generate long-term charts
        run: |
          python scripts/long_charts.py
          ls -lah "$OUT_DIR" || true

      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global safe.directory "$(pwd)"
          git add "$OUT_DIR"/rbank9_{7d,1m,1y}.png "$OUT_DIR"/_last_run.txt 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(rbank9): update long-term charts (7d/1m/1y)"
            git push
          fi
