name: Update history & long-term charts

on:
  schedule:
    # JST 15:40 (UTC は -9h → 06:40)
    - cron: '40 06 * * 1-5'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [rbank9, scoin_plus, astra4, ain10]  # 必要なものだけに減らしてOK

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install pandas pytz matplotlib

      - name: Append today's history
        env:
          INDEX_KEY: ${{ matrix.index }}
        run: |
          python scripts/update_history.py

      - name: Generate long-term charts (1d/7d/1m/1y)
        env:
          INDEX_KEY: ${{ matrix.index }}
        run: |
          python scripts/long_charts.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(charts): update history & long-term charts (${{ matrix.index }})"
          file_pattern: |
            docs/outputs/${{ matrix.index }}_history.csv
            docs/outputs/${{ matrix.index }}_*.png
